import pandas as pd
import os

# Lista con todas las rutas de tus archivos CSV
rutas = [
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Alan\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Camilo\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Carlos\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Diego\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Fernando\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Guillermina\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Ixchel\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Jose\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Juan\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Luis Leonardo\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Manuel\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Minerva\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Rosa\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Sandra\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Torres\files\caracteristicass_3_ventanas_caminar_3.csv",
##
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_sentarse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_sentarse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_sentarse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_pararse_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_pararse_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_pararse_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_aplaudir_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_aplaudir_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_aplaudir_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_saludar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_saludar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_saludar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_martillar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_martillar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_martillar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_dibujar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_dibujar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_dibujar_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_telefono_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_telefono_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_telefono_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_hora_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_hora_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_hora_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_beber_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_beber_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_beber_3.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_caminar_1.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_caminar_2.csv",
r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\Uriel\files\caracteristicass_3_ventanas_caminar_3.csv",
##
]


# Lista para almacenar todos los DataFrames
df_total = []

for ruta in rutas:
    # Cargar CSV
    df = pd.read_csv(ruta)

    # Obtener el nombre de la persona desde el path
    partes_ruta = ruta.split(os.sep)
    persona = partes_ruta[-3]  # Ej: 'Minerva'

    # Extraer nombre del archivo
    nombre_archivo = os.path.basename(ruta)  # Ej: 'caracteristicass_sentarse_1.csv'
    partes = nombre_archivo.replace(".csv", "").split("_")
    
    actividad = partes[1]  # Ej: 'sentarse'
    repeticion = partes[2]  # Ej: '1'

    # Añadir columnas
    df["persona"] = persona
    df["actividad"] = actividad
    df["repeticion"] = repeticion

    df_total.append(df)

# Unir todo
df_final = pd.concat(df_total, ignore_index=True)

# Guardar CSV final
salida = r"C:\Users\rafae\Desktop\aprendizaje\PF_Frias_Cortez_Rafael_Alejandro\caracteristicas_completo_filtro_3_ventanas.csv"
df_final.to_csv(salida, index=False)

print("CSV combinado guardado en:", salida)
